# Generated by Django 4.2.18 on 2025-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='over_due_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrow',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
