# Generated by Django 4.2.18 on 2025-01-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrow_over_due_days_borrow_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='remaining_days',
        ),
    ]
