# Generated by Django 4.2.18 on 2025-01-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_remove_borrow_penalty_remove_borrow_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='over_due_days',
        ),
    ]
